server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.h2.driver
    password: sa
    url: jdbc:h2:mem:tesdb
    username: sa
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
app:
    messages:
      contactSavesuccess:contact has been saved
      contactsavefail:contact not saved
      contactdeleted:contact has been deleted
      contactdelefail:contact deleted failed